spring:
  kafka:
    bootstrap-servers: localhost:9194
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - localhost:9194
      bindings:
        orderCreated-out-0:
          destination: order-topic
          content-type: application/json        
  application:
    name: order-service

server:
  port: 8082
