eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8585/realms/turkcell-p1-dev
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9194
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - localhost:9194
      bindings:
        orderCreated-in-0:
          destination: order-topic
          group: product-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  