spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mehmetfatihkavala/4.5-project.git
          default-label: main
          search-paths:
            - configurations/
            - configurations/{application}

server:
  port: 8787


